In [ ]:
# JupyterLite needs openpyxl to read Excel files
%pip install -q openpyxl

# Calculating price elasticity of milk across two markets

A supermarket chain sells across two markets: Europe and Asia. They are considering an increase in the price of milk, to account for the increasing costs of the supply chains. Before they increase the prices, the economists advising the supermarket CEO want to study the price elasticity of milk across the two markets, so see which market will be more heavily impacted by the increase.

In [1]:
# Start by reading the data from PriceElasticity.xlsx

import pandas as pd

milk_price_demand = pd.read_excel('PriceElasticity.xlsx')
milk_price_demand.head()

   Price / l  Europe Sales (Ml)  Asia Sales (Ml)
0       0.60               6798             5359
1       0.61               6562             5624
2       0.62               6369             5425
3       0.63               6335             5167
4       0.64               6391             5553

In [2]:
# Discover the correlations between the fields in the data

milk_price_demand.corr()

                   Price / l  Europe Sales (Ml)  Asia Sales (Ml)
Price / l           1.000000          -0.997156        -0.988038
Europe Sales (Ml)  -0.997156           1.000000         0.986104
Asia Sales (Ml)    -0.988038           0.986104         1.000000

There is a strong correlation between the Price per litre and the Sales across each region (measured in millions of litres). We can therefore use the price to build a linear regression for sales in each region.

This will mean building two separate linear regression models: one for Europe and one for Asia.

##### Building the Europe model

In [5]:
dependent = milk_price_demand['Europe Sales (Ml)']
independent = milk_price_demand['Price / l']

In [6]:
import statsmodels.api as sm

independent = sm.add_constant(independent)

In [7]:
import statsmodels.api as sm

# Build the model

model_eu = sm.OLS(
    dependent, 
    independent
).fit()

# Print model summary statistics

model_eu.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      Europe Sales (Ml)   R-squared:                       0.994
Model:                            OLS   Adj. R-squared:                  0.994
Method:                 Least Squares   F-statistic:                 1.838e+04
Date:                Mon, 26 Sep 2022   Prob (F-statistic):          9.91e-120
Time:                        17:22:10   Log-Likelihood:                -680.09
No. Observations:                 107   AIC:                             1364.
Df Residuals:                     105   BIC:                             1370.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.021e+04     51.583    197.876      0.000    1.01e+04    1.03e+04
Price / l  -5969.7329     44.033   -135.573      0.000   -6057.043   -5882.423
==============================================================================
Omnibus:                       12.165   Durbin-Watson:                   1.907
Prob(Omnibus):                  0.002   Jarque-Bera (JB):                4.053
Skew:                           0.060   Prob(JB):                        0.132
Kurtosis:                       2.054   Cond. No.                         7.55
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

##### Building the Asia model

In [8]:
dependent = milk_price_demand['Asia Sales (Ml)']
independent = milk_price_demand['Price / l']

In [9]:
import statsmodels.api as sm

independent = sm.add_constant(independent)

In [10]:
import statsmodels.api as sm

# Build the model

model_as = sm.OLS(
    dependent, 
    independent
).fit()

# Print model summary statistics

model_as.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:        Asia Sales (Ml)   R-squared:                       0.976
Model:                            OLS   Adj. R-squared:                  0.976
Method:                 Least Squares   F-statistic:                     4310.
Date:                Mon, 26 Sep 2022   Prob (F-statistic):           4.43e-87
Time:                        17:23:21   Log-Likelihood:                -680.16
No. Observations:                 107   AIC:                             1364.
Df Residuals:                     105   BIC:                             1370.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       7139.0447     51.612    138.321      0.000    7036.707    7241.382
Price / l  -2892.6125     44.058    -65.654      0.000   -2979.972   -2805.253
==============================================================================
Omnibus:                       13.454   Durbin-Watson:                   2.106
Prob(Omnibus):                  0.001   Jarque-Bera (JB):                4.250
Skew:                          -0.058   Prob(JB):                        0.119
Kurtosis:                       2.031   Cond. No.                         7.55
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

##### Calculating Price Elasticity of Demand

The Price Elasticity of Demand (PED) is calculated as:

$$\text{PED} = \frac{\text{current price}}{\text{current quantity}}\times \text{Coefficient of Price}$$

The current average price of milk in Europe and Asia is €1.43. We can calculate the price elasticity in each market:

**Europe:**
$$\text{PED} = \frac{1.43}{10210 - 5970 \times 1.43} \times (-5970)$$

In [12]:
1.43/(10210-5970*1.43)*(-5970)

-5.103174128758444

**Asia:**
$$\text{PED} = \frac{1.43}{7139 - 2893 \times 1.43} \times (-2893)$$

In [13]:
1.43/(7139-2893*1.43)*(-2893)

-1.37807335751713