# Read in the Data To Python

In [13]:
import pandas as pd

In [15]:
meta_stock = pd.read_csv('Meta_stock_log_5_6.csv')
meta_stock.head()

,Date,Open,Close,Up/Down,Change in stock price,Actual up/down tomorrow
0,28/04/2016,119.580002,116.730003,Down,-2.849999,1
1,29/04/2016,116.820000,117.580002,Up,0.760002,1
2,02/05/2016,117.830002,118.570000,Up,0.739998,0
3,03/05/2016,117.519997,117.430000,Down,-0.089997,1
4,04/05/2016,116.610001,118.059998,Up,1.449997,0

# 5.6 When is a logistic Regression appropriate

In [16]:
meta_stock.columns

Index(['Date', 'Open', 'Close', 'Up/Down', 'Change in stock price',
       'Actual up/down tomorrow'],
      dtype='object')

In [17]:
meta_stock[['Open', 
            'Close',
            'Change in stock price',
            'Actual up/down tomorrow'
           ]].groupby('Actual up/down tomorrow').mean()

                               Open       Close  Change in stock price
Actual up/down tomorrow
0                        206.806923  207.109136               0.302214
1                        201.655195  201.460156              -0.195039

In [20]:
import scipy.stats as stats

group1 = meta_stock[meta_stock['Actual up/down tomorrow'] == 0]

group2 = meta_stock[meta_stock['Actual up/down tomorrow'] == 1]

stats.ttest_ind(group1['Change in stock price'], group2['Change in stock price'])

TtestResult(statistic=2.796991368627499, pvalue=0.005223560471676602, df=1509.0)